tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/bundle"

brew "bash-completion"
brew "gcc"
brew "git"
brew "htop"
brew "mas"
brew "node"
brew "openssh"
brew "python"
brew "python@2"
brew "tree"
brew "vim"
brew "youtube-dl"

cask "apptrap"
cask "coconutbattery"
cask "cyberduck"
cask "discord"
cask "eclipse-platform"
cask "flux"
cask "google-backup-and-sync"
cask "java"
cask "music-manager"
cask "openoffice"
cask "shiftit"
cask "skype"
cask "torbrowser"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "xquartz"

cask "homebrew/cask-versions/google-chrome-dev"
cask "homebrew/cask-versions/iterm2-beta"
cask "homebrew/cask-versions/keka-beta"
cask "homebrew/cask-versions/microsoft-remote-desktop-beta"

mas "GarageBand", id: 682658836
